name = "cloudflare-ip-loggerr"
compatibility_date = "2024-02-18"

# Environment Variables (Remove if unused)
[vars]
LOG_ENDPOINT = "https://your-logging-endpoint.com"

# Declare KV Namespace (Only once)
[[kv_namespaces]]
binding = "IP_LOGGER"
id = "ip-loggerrr"
