name = "cloudflare-ip-loggerr"
compatibility_date = "2024-02-18"

[vars]
LOG_ENDPOINT = "https://your-logging-endpoint.com"

# Declare KV Namespace
[[kv_namespaces]]
binding = "IP_LOGGER"
id = "ip-loggerrr"

[env.production]
kv_namespaces = [
  { binding = "IP_LOGGER", id = "ip-loggerrr" }
]
